<?php

/**
 * @file
 * Contains shorthand.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityFieldManagerInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\shorthand\Controller\RemoteCollectionController;

/**
 * Implements hook_help().
 */
function shorthand_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  // Help for the shorthand module.
  if ($route_name == 'help.page.shorthand') {
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('A module that allows the publishing of Shorthand stories directly to Drupal entities.') . '</p><ul>';
    $output .= '<li>' . t('Login to <em>shorthand account</em> and <em>generate API key</em> (links are in README.md file).') . '</li>';
    $output .= '<li>' . t('Visit configuration page at <em>/admin/config/services/shorthand</em> to set API key and other settings.') . '</li>';
    $output .= '<li>' . t('Download remote stories locally at <em>/admin/content/shorthand</em>.') . '</li>';
    $output .= '<li>' . t('Add <em>Shorthand select</em> field (`Reference` field category) to desired entity (content type, taxonomy term, user, ...).') . '</li>';
    $output .= '<li>' . t('When managing entity with Shorthand field, select one of the
downloaded stories.') . '</li>';
    $output .= '</ul>';
  }

  return $output;
}

/**
 * Implements hook_metatags_alter().
 */
function shorthand_metatags_alter(array &$metatags, array &$context) {
  if (!\Drupal::moduleHandler()->moduleExists('metatag')) {
    return;
  }

  // Ignore some system routes that are not appropriate for meta tags.
  if (metatag_is_current_route_supported()
    && $context['entity']
    && $context['entity'] instanceof FieldableEntityInterface) {
    $entity = $context['entity'];
    $supportedEntities = \Drupal::service(EntityFieldManagerInterface::class)->getFieldMapByFieldType('shorthand_local');
    if (!array_key_exists($entity->getEntityTypeId(), $supportedEntities)) {
      return;
    }
    $fields = $supportedEntities[$entity->getEntityTypeId()];
    foreach ($fields as $name => $detail) {
      if (!in_array($entity->bundle(), $detail['bundles'])) {
        continue;
      }

      if ($path = $entity->get($name)->value) {
        // Parse metatags.
        $filePathHead = 'public://' . RemoteCollectionController::SHORTHAND_STORY_BASE_PATH . '/' . $path . '/head.html';

        if (!file_exists($filePathHead)) {
          continue;
        }

        $doc = Html::load(file_get_contents($filePathHead));
        $xpath = new DOMXPath($doc);
        foreach ($xpath->query('//meta') as $node) {
          $attributes = [];
          if ($node->attributes) {
            foreach ($node->attributes as $attribute) {
              $attributes[$attribute->name] = $attribute->value;
            }

            // Ignore meta tags that don't have content and one of name or
            // property attributes.
            if (array_key_exists('content', $attributes) &&
              (array_key_exists('property', $attributes) || array_key_exists('name', $attributes))) {
              $metaname = str_replace(['og:', 'twitter:'], ['og_', 'twitter_cards_'], $attributes['property'] ?? $attributes['name']);
              if ($metaname === 'generator') {
                // Skip generator.
                continue;
              }
              // Make sure tag is not set in Drupal.
              if (!array_key_exists($metaname, $metatags)) {
                $metatags[$metaname] = $attributes['content'];
              }

              // Modify image tokens.
              if (in_array($metaname,
                  [
                    'twitter_cards_image',
                    'og_image',
                  ],
                  TRUE
                ) && strlen($attributes['content'])) {
                $content = explode('/assets/', $attributes['content']);
                if (is_array($content) && count($content) > 1) {
                  $metatags[$metaname] = \Drupal::service('file_url_generator')
                    ->generateAbsoluteString('public://' . RemoteCollectionController::SHORTHAND_STORY_BASE_PATH . '/' . $path . '/assets/' . $content[1]);
                }
              }
            }
          }
        }
      }
    }
  }
}
