<?php

/**
 * @file
 * Shorthand module .install file.
 */

use Drupal\shorthand\Entity\ShorthandStory;

/**
 * Uninstall tasks.
 */
function shorthand_uninstall() {
  // Existing stories deletion is already handled by the module uninstaller, so
  // remove just the files/shorthand folder, if exists.
  \Drupal::service('file_system')->deleteRecursive('public://' . ShorthandStory::SHORTHAND_STORY_BASE_PATH);
}
