# Schema for the configuration files of the shorthand module.

shorthand.settings:
  type: config_object
  label: 'Shorthand settings'
  mapping:
    shorthand_token:
      type: string
      label: 'Shorthand API token'
    shorthand_request_timeout:
      type: integer
      label: 'Shorthand request timeout'
    shorthand_input_format:
      type: string
      label: 'Text field format'
